version: 2
jobs:
    library:
        working_directory: ~/nnlib
        docker:
            - image: circleci/python:3.6.6-stretch-browsers
        steps:
            - checkout:
                path: ~/nnlib
            - restore_cache:
                key: server-deps-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "dev-requirements.txt" }}
            - run: python3 -m venv ~/.venv
            - run:
                command: |
                    source ~/.venv/bin/activate
                    pip install -r dev-requirements.txt
            - run:
                command: |
                    source ~/.venv/bin/activate
                    pip install -r requirements.txt
            - run:
                command: |
                    source ~/.venv/bin/activate
                    pip install -e .
            - run:
                command: |
                    source ~/.venv/bin/activate
                    flake8
            - run:
                command: |
                    source ~/.venv/bin/activate
                    pytest -vvvv -s -r a
            - save_cache:
                key: server-deps-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "dev-requirements.txt" }}
                paths:
                    - ~/.venv
workflows:
    version: 2
    test_and_lint:
        jobs:
            - library
